services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: panel-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    env_file:
      - .env
    networks:
      - laravel-network

  # Nginx Web Server
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: panel-web
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - laravel-network

  # Queue Worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: panel-worker
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=360
    working_dir: /var/www
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
